// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw-wSBErtwmF-YF8XtMX3hFtezvD69P9w',
    appId: '1:1045467121720:ios:bad2f14b6769c2e72d7ecd',
    messagingSenderId: '1045467121720',
    projectId: 'mini-blog-app-3ff95',
    storageBucket: 'mini-blog-app-3ff95.firebasestorage.app',
    iosBundleId: 'com.josiaskiesse17gmail.miniBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw-wSBErtwmF-YF8XtMX3hFtezvD69P9w',
    appId: '1:1045467121720:ios:bad2f14b6769c2e72d7ecd',
    messagingSenderId: '1045467121720',
    projectId: 'mini-blog-app-3ff95',
    storageBucket: 'mini-blog-app-3ff95.firebasestorage.app',
    iosBundleId: 'com.josiaskiesse17gmail.miniBlogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCh9O6evpcsEUpMlQ4_fu-GAby7wCho3jk',
    appId: '1:1045467121720:web:847d82fc86d510c72d7ecd',
    messagingSenderId: '1045467121720',
    projectId: 'mini-blog-app-3ff95',
    authDomain: 'mini-blog-app-3ff95.firebaseapp.com',
    storageBucket: 'mini-blog-app-3ff95.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh9O6evpcsEUpMlQ4_fu-GAby7wCho3jk',
    appId: '1:1045467121720:web:847d82fc86d510c72d7ecd',
    messagingSenderId: '1045467121720',
    projectId: 'mini-blog-app-3ff95',
    authDomain: 'mini-blog-app-3ff95.firebaseapp.com',
    storageBucket: 'mini-blog-app-3ff95.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCh9O6evpcsEUpMlQ4_fu-GAby7wCho3jk',
    appId: '1:1045467121720:web:847d82fc86d510c72d7ecd',
    messagingSenderId: '1045467121720',
    projectId: 'mini-blog-app-3ff95',
    authDomain: 'mini-blog-app-3ff95.firebaseapp.com',
    storageBucket: 'mini-blog-app-3ff95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByOtOOKfMr2TnEm1fVU8XkosZOR6A56Eo',
    appId: '1:1045467121720:android:9e57b8bc66741db12d7ecd',
    messagingSenderId: '1045467121720',
    projectId: 'mini-blog-app-3ff95',
    storageBucket: 'mini-blog-app-3ff95.firebasestorage.app',
  );
}
